### ISSUE TITLE
How to use with Gunicorn?

### ISSUE THREAD

**Issue by naechtner** [SAP/cf-python-logging-support#10]
Hi,

Is it possible to use this with gunicorn, if so, is there an example for that?

Best
Nico

**Comment by gvachkov** [comment]
Hi Nico,

The library is not supporting integration with gunicorn currently (at least not tested on our side).
We will investigate an probably plan the support for it.

best regards,
Georgi

**Comment by georgi-bozhinov** [comment]
Hello Nico,

What is your use case for gunicorn? If running a Flask/Falcon/Sanic app with gunicorn, it will emit the same logs that the apps themselves will. The only difference would be the worker logs. 

Best regards,
Georgi

**Comment by desgovedarska** [comment]
This is pretty old, so I'm closing it. Please reopen, if you have further questions.
