### ISSUE TITLE
Problem with object logging

### ISSUE THREAD

**Issue by Stockemer** [SAP/cf-python-logging-support#12]
Hello,

we run into trouble using this package in combination with the pika package (http://pika.readthedocs.io/en/0.10.0/). After initialization of the logger using cf_logging.init() the pika packages produces exceptions while trying to perform the following log operation: 

LOGGER.info('Closing channel (%s): %r on %s',
                    reply_code, reply_text, self)

Here 'reply_code' is an int, 'reply_text' a string and 'self' is the channel object which has a working __repr__ method. 

Best 
Jan

**Comment by gvachkov** [comment]
Hi Jan, I managed to reproduce the issue and will check how this could be fixed.

best regards,
Georgi

**Comment by Stockemer** [comment]
Hey Georgi,

Thanks a lot! :)

2018-04-11 11:10 GMT+02:00 Georgi Vachkov <notifications@github.com>:
