### ISSUE TITLE
Cloud foundry logs msg field with additional fields.

### ISSUE THREAD

**Issue by MikoLasso123** [SAP/cf-python-logging-support#41]
Im using a flask app with cloudfoundry and the logs show a bunch of additional fields inside the msg:, eventhough these fields are to be found as separate fields in the log record. What is the best way to remove these fields from msg: and just keep that field clean.

**Comment by alexpenev-s** [comment]
Hello, Could you please give an example of how you log it and what you get?
When I try it out I get:
"msg": "Hi", "REQUEST_KEY": "a"
Where REQUEST_KEY is passed as an extra field.
