### ISSUE TITLE
Extra fields sent via the logging API are not visible in Kibana

### ISSUE THREAD

**Issue by jeffjzf** [SAP/cf-python-logging-support#45]
Steps to reproduce the issue:
Use sap_cf_logging==4.0.1 package to call the logging methods in python.
Add extra log fields
logging_extra = { 'TEST_FIELD': 'TEST_VALUE' }
logger.info('TEST MSG', extra=logging_extra)

These fields are viewable in CF cockpit but are removed/cleanedUp in Kibana after the SAP Cloud platform release in July 2020.
SAP Cloud Platform Release notes(Search for Application Logging):
https://help.sap.com/doc/DRAFT/e5e48c84bccd43509bee3087ebcc7bc6/Internal/en-US/98bf747111574187a7c76f8ced51cfeb.html?date=2020-07-16

**Comment by alexpenev-s** [comment]
Implemented custom fields #46
