### ISSUE TITLE
get/set property to log without HTTP request context

### ISSUE THREAD

**Issue by luisfelipe998** [SAP/cf-python-logging-support#47]
I have an app which does not use HTTP and I would like to set a property to be displayed at kibana, e.g. the `tenant_id` one. 

Looking at the internals of the library, I saw the `job_logging` package which looks like the one being used when there are no http context provided.
I tried to call the methods as follows:
```
from sap import cf_logging

cf_logging.FRAMEWORK.context.set('tenant_id', 'test_value', None)
print(cf_logging.FRAMEWORK.context.get('tenant_id', None))
```

Although the property was set, it was not correctly logged on the JSON log, nor the `tenant_id` was populated on the kibana dashboard.
What am I doing wrong here? Is there other way to set/get properties from the log object that I missed?

**Comment by alexpenev-s** [comment]
Hello, 
Here is an example how to log the tenant_id:
```python
import logging
from sap import cf_logging

cf_logging.init()

logger = logging.getLogger("cli.logger")
extra = {'tenant_id': 'my_value'}
logger.info('hi', extra=extra)
```

In the output you should see: (at the root level of the json log object)
```json
"tenant_id": "my_value"
```

There are no default values here. You have to specify each time when you log the key/value pair.

**Comment by luisfelipe998** [comment]
Yes, that worked. Thank you 🤝
