### ISSUE TITLE
line_no removed in b25943a3a57f75e942f643769abef8f22158ffe4

### ISSUE THREAD

**Issue by mhaas** [SAP/cf-python-logging-support#60]
Commit b25943a3a57f75e942f643769abef8f22158ffe4 removes `line_no` from `SimpleLogRecord`.

Can I ask why this is the case?

We were using that in our custom plain text log formatter, which we need to convert the logs from JSON to human-readable plaintext when running locally. It is good to have the line number when debugging locally.

**Comment by alexpenev-s** [comment]
Hello, the library is primarily used for viewing logs in Kibana. The field line_no was not being displayed as it's not part of the schema.
I believe it was being removed with a warning (if I remember correctly).
That was the original reason to remove it. 
I don't see a problem with putting the field back.

**Comment by mhaas** [comment]
Thanks - we no longer depend on line_no. I will close this issue and update to the latest :)
