### ISSUE TITLE
Formatting issue with embedded msg?

### ISSUE THREAD

**Issue by altenhof** [SAP/cf-python-logging-support#7]
Hi,

just came across log samples written with your library that seem to be not formatted correctly. More specifically, the nested `msg` fields seems to lack proper escaping:
```
\"msg\":\"1.2.3.4 - - [04/Jan/2018 11:04:22] \"POST /inference_sync HTTP/1.1\" 200 -\",
```
If I'm not completely mistaken, the part `\"POST...HTTP/1.1\"` should be `\\\"POST...\\\"`.

As it is not, the logstash JSON filter reports the following error:

```
Unexpected character ('P' (code 80)): was expecting comma to separate Object entries
```

Best

Michael

**Comment by thangbn** [comment]
hi Micheal,
I will take a look

**Comment by gvachkov** [comment]
Hi Michael, this should be fixed with the latest version of the library.
